apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgresql-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: postgresql
    tier: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgresql
      tier: backend
  template:
    metadata:
      labels:
        app: postgresql
        tier: backend
    spec:
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: my-pvc
      containers:
        - name: postgresql-pod
          image: bitnami/postgresql:latest
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgresql-data
          ports:
            - name: postgres-server
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresql-configmap

