# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgresql-secret
#   namespace: {{ .Values.namespace }}
# data:
#   {{- if .Values.adminPassword }}
#   POSTGRESQL_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
#   {{- else }}
#   POSTGRESQL_PASSWORD: {{ randAlphaNum 8 | b64enc | quote }}
#   {{- end }}
