apiVersion: v1
kind: Secret
metadata:
  name: ckan-secret
  namespace: {{ .Values.namespace }}
data:
  {{- if .Values.adminPassword }}
  POSTGRESQL_DATABASE_USER_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
  POSTGRESQL_DATASTORE_USER_WRITE_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
  POSTGRESQL_DATASTORE_USER_READ_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
  CKAN_ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  POSTGRESQL_DATABASE_USER_PASSWORD: {{ randAlphaNum 8 | b64enc | quote }}
  {{- end }}
