apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app: postgresql
    tier: backend
spec:
  ports:
  - port: 5432
    targetPort: postgres-server
  selector:
    app: postgresql
    tier: backend
  type: ClusterIP
