apiVersion: v1
kind: Service
metadata:
  name: ckan-service
  labels:
    app: ckan
    tier: frontend
spec:
  ports:
  - port: 5050
    targetPort: ckan-server
  selector:
    app: ckan
    tier: frontend
  type: NodePort
