apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: s3d1
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
